### PR TITLE
[Android] Base 64 input/output, fit option 

### PR DESCRIPTION
**Pull request by kdcro101**
@JoschkaSchulz,

Here is PR I've mentioned in issue https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/issues/37.

### Changes
- accept base64 data-uri as input
- option fit to fit input image within bounds (options.width and options.height)
- output as base64 string

### CODE REVIEW

**Comment by jayordway** [comment]
When will this be released?

**Comment by kdcro101** [comment]
@jayordway,

Waiting for @JoschkaSchulz  to react.. 
He agreed with PR @ https://github.com/JoschkaSchulz/cordova-plugin-image-resizer/issues/37

**Comment by JoschkaSchulz** [comment]
Hey, sorry for the long response... are you able to clean up the history a bit... it seems that there could be much squash. After that I would create a new version. 👍 Thank you very much

**Comment by JoschkaSchulz** [comment]
This is already merged

**Pull request closed without merging**
